import z from "zod";

export const CurrentWeatherSchema = z.object({
  time: z.string(),
  temperature_2m: z.number(),
  relative_humidity_2m: z.number().optional(),
  apparent_temperature: z.number().optional(),
  precipitation: z.number().optional(),
  weather_code: z.number().optional(),
  cloud_cover: z.number().optional(),
  wind_speed_10m: z.number().optional(),
  wind_direction_10m: z.number().optional(),
  visibility: z.number().optional(),
  is_day: z.number().optional(),
  uv_index: z.number().optional(),
  pressure_msl: z.number().optional(),
});

export const HourlyWeatherSchema = z.object({
  time: z.array(z.string()),
  temperature_2m: z.array(z.number()),
  relative_humidity_2m: z.array(z.number()).optional(),
  apparent_temperature: z.array(z.number()).optional(),
  precipitation: z.array(z.number()).optional(),
  weather_code: z.array(z.number()).optional(),
  cloud_cover: z.array(z.number()).optional(),
  wind_speed_10m: z.array(z.number()).optional(),
  wind_direction_10m: z.array(z.number()).optional(),
  visibility: z.array(z.number()).optional(),
  is_day: z.array(z.number()).optional(),
  uv_index: z.array(z.number()).optional(),
  pressure_msl: z.array(z.number()).optional(),
});

export const DailyWeatherSchema = z.object({
  time: z.array(z.string()),
  weather_code: z.array(z.number()),
  temperature_2m_max: z.array(z.number()),
  temperature_2m_min: z.array(z.number()),
  apparent_temperature_max: z.array(z.number()).optional(),
  apparent_temperature_min: z.array(z.number()).optional(),
  sunrise: z.array(z.string()),
  sunset: z.array(z.string()),
  precipitation_sum: z.array(z.number()),
  wind_speed_10m_max: z.array(z.number()),
  wind_direction_10m_dominant: z.array(z.number()).optional(),
  uv_index_max: z.array(z.number()).optional(),
  precipitation_hours: z.array(z.number()).optional(),
});

export const WeatherForecastSchema = z.object({
  latitude: z.number(),
  longitude: z.number(),
  generationtime_ms: z.number(),
  utc_offset_seconds: z.number(),
  timezone: z.string(),
  timezone_abbreviation: z.string(),
  elevation: z.number(),
  current: CurrentWeatherSchema,
  hourly_units: z.object({
    time: z.string(),
    temperature_2m: z.string().optional(),
    relative_humidity_2m: z.string().optional(),
    apparent_temperature: z.string().optional(),
    precipitation: z.string().optional(),
    weather_code: z.string().optional(),
    cloud_cover: z.string().optional(),
    wind_speed_10m: z.string().optional(),
    wind_direction_10m: z.string().optional(),
    visibility: z.string().optional(),
    is_day: z.string().optional(),
    uv_index: z.string().optional(),
    pressure_msl: z.string().optional(),
  }).optional(),
  hourly: HourlyWeatherSchema.optional(),
  daily_units: z.object({
    time: z.string(),
    weather_code: z.string(),
    temperature_2m_max: z.string(),
    temperature_2m_min: z.string(),
    apparent_temperature_max: z.string().optional(),
    apparent_temperature_min: z.string().optional(),
    sunrise: z.string(),
    sunset: z.string(),
    precipitation_sum: z.string(),
    wind_speed_10m_max: z.string(),
    wind_direction_10m_dominant: z.string().optional(),
    uv_index_max: z.string().optional(),
    precipitation_hours: z.string().optional(),
  }).optional(),
  daily: DailyWeatherSchema.optional(),
}).transform((data) => ({
  ...data,
  current_weather: {
    time: data.current.time,
    temperature: data.current.temperature_2m,
    windspeed: data.current.wind_speed_10m || 0,
    winddirection: data.current.wind_direction_10m || 0,
    weathercode: data.current.weather_code || 0,
    is_day: data.current.is_day || 0,
  }
}));